# Generated by Django 3.1.1 on 2020-09-04 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('offer', 'Offer'), ('offer_denied', 'Offer Denied'), ('contract_funded', 'Contract Funded'), ('released', 'Released'), ('dispute', 'Dispute'), ('released_by_arbitrator', 'Released By Arbitrator')], default='offer', max_length=23)),
                ('offer_accepted', models.BooleanField(blank=True, null=True)),
                ('party_making_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_made', to=settings.AUTH_USER_MODEL)),
                ('party_released_escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_released', to=settings.AUTH_USER_MODEL)),
                ('party_taking_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_accepted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
