# Generated by Django 3.1.1 on 2020-09-04 11:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_amount',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('10.0'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_terms',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
