# Generated by Django 3.1.1 on 2020-09-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapp', '0003_auto_20200904_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('offer', 'Offer'), ('accepted', 'Accepted'), ('offer_declined', 'Offer Declined'), ('contract_funded', 'Contract Funded'), ('released', 'Released'), ('dispute', 'Dispute'), ('released_by_arbitrator', 'Released By Arbitrator')], default='offer', max_length=23),
        ),
    ]
