# Generated by Django 3.1.1 on 2020-09-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapp', '0004_auto_20200904_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='token',
            field=models.CharField(choices=[('4de69e374a8ed21cbddd47f2338cc0f479dc58daa2bbe11cd604ca488eca0ddf', 'SPICE Token'), ('c4b0d62156b3fa5c8f3436079b5394f7edc1bef5dc1cd2f9d0c4d46f82cca479', 'USDH Token'), ('9fc89d6b7d5be2eac0b3787c5b8236bca5de641b5bafafc8f450727b63615c11', 'USDt Token (BCH network)')], default='', max_length=64),
            preserve_default=False,
        ),
    ]
