# Generated by Django 3.1.1 on 2020-09-05 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escrowapp', '0005_contract_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='party_released_escrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_released', to=settings.AUTH_USER_MODEL),
        ),
    ]
