# Generated by Django 3.1.1 on 2020-09-06 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escrowapp', '0007_auto_20200906_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='party_contract_released_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_released_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
